### ISSUE TITLE
Drop Python 2.6 / 3.2 support

### ISSUE THREAD

**Issue by tseaver** [buildout/buildout#297]
3.2 isn't supported by currrent setuptools;  2.6 is long out-of-maintenance.

**Comment by do3cc** [comment]
Support for 2.6 has now de facto been removed, because the latest change and latest release has test failures with python 2.6. The fastest fix would be to remove python 2.6 support

**Comment by do3cc** [comment]
I't seems 3.3 is also not supported any more. I've updated PR.

**Comment by reinout** [comment]
I don't see it in the PR. Did you push it? Or is it perhaps because I already merged it?

And can you look at Tres' comment about updating the python 2.7 version?

**Comment by do3cc** [comment]
I made a new PR with all patch versions updated. Python 3.3 still gets security fixes but it isn't listed on the plone releases page, so I kicked it.

**Comment by mauritsvanrees** [comment]
The new PR #304 was merged too.
This issue can be closed.
